var svgw = window.innerWidth;
var autofontsize = 0.015 * svgw;
var leftpad=0.02*svgw;
var tempstr="<div class='row-fluid' style='padding-top:"+leftpad+"px;margin-left:"+leftpad+"px;margin-right:"+leftpad+"px'>";
tempstr=tempstr+"	<h4><span data-i18n-text='welcome'></span> <span id='block_trans' style='display:none;color:#0084cc !important;'><small>";
tempstr=tempstr+"(<span id='s_lastestheight'></span><span style='margin-left:5px' data-i18n-text='LastBlockheight'></span>,";
tempstr=tempstr+" <span style='margin-left:5px' id='s_trans'></span><span style='margin-left:5px' data-i18n-text='Transactions'></span>, ";
tempstr=tempstr+"<span style='margin-left:5px' id='s_addrs'></span><span style='margin-left:5px' data-i18n-text='CountAddres'></span>)";
tempstr=tempstr+"</span></small></h4>";
document.writeln(tempstr);
document.writeln("	<div class='input-group'>");
document.writeln("		<span class=\'input-group-btn\'><label class=\'btn btncolor\'>&nbsp;&nbsp;SLU&nbsp;&nbsp;</label></span><span><input");
document.writeln("			id=\'searchkeys\' type=\'text\' class=\'form-control\'");
document.writeln("			data-i18n-placeholder=\'SearchTips\'> </span><span");
document.writeln("			class=\'input-group-btn\'>");
document.writeln("			<button id=\'searchbtn\' class=\'btn btncolor\' type=\'button\'>");
document.writeln("				<span class=\'glyphicon glyphicon-search\'></span>");
document.writeln("			</button>");
document.writeln("		</span>");
document.writeln("	</div>");
document.writeln("</div>");